# Generated by Django 6.0 on 2026-01-13 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, unique=True, verbose_name='Lagerort')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200, verbose_name='Rezept')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Quelle')),
                ('preparation_time', models.CharField(max_length=100, verbose_name='Zubereitungszeit')),
                ('cooking_time', models.CharField(blank=True, max_length=100, verbose_name='Koch/Backzeit')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('experimental', models.BooleanField(default=False, verbose_name='Noch in Erprobung')),
                ('sweet', models.BooleanField(default=False, verbose_name='Süß')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200, unique=True, verbose_name='Zutat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto')),
                ('usually_stocked', models.BooleanField(default=True, verbose_name='normalerweise vorhanden')),
                ('alternatives', models.CharField(blank=True, max_length=200, verbose_name='Mögliche Alternative(n)')),
                ('location1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location1', to='recipes.location', verbose_name='Lagerort')),
                ('location2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location2', to='recipes.location', verbose_name='Alternativer Lagerort')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Rezept')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Text')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step', verbose_name='Schritt')),
            ],
        ),
        migrations.CreateModel(
            name='StepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200, verbose_name='Menge')),
                ('unit', models.CharField(max_length=100, verbose_name='Einheit')),
                ('alternatives', models.CharField(blank=True, max_length=200, verbose_name='Mögliche Alternative(n)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Zutat')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step', verbose_name='Schritt')),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utensil_name', models.CharField(max_length=200, unique=True, verbose_name='Utensil')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.location', verbose_name='Lagerort')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUtensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Rezept')),
                ('utensil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.utensil', verbose_name='Utensil')),
            ],
        ),
    ]
