# Generated by Django 6.0 on 2026-01-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Einheit'),
        ),
    ]
