# Generated by Django 6.0 on 2025-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time_alter_recipe_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='alternatives',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
