# Generated by Django 6.0 on 2025-12-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_location_alter_ingredient_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='instruction_text',
            new_name='text',
        ),
    ]
