# Generated by Django 6.0 on 2025-12-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_utensil_recipeutensil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='step_number',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='StepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
                ('alternatives', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step')),
            ],
        ),
        migrations.CreateModel(
            name='StepInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.instruction')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientInRecipe',
        ),
    ]
