# Generated by Django 6.0 on 2025-12-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_instruction_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepinstruction',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='stepinstruction',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='StepInstruction',
        ),
    ]
