# Generated by Django 6.0 on 2025-12-25 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_stepinstruction_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='experimental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
