# Generated by Django 6.0 on 2025-12-26 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_experimental_recipe_sweet_alter_step_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='instruction',
        ),
        migrations.CreateModel(
            name='StepInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.instruction')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step')),
            ],
        ),
    ]
