# Generated by Django 6.0 on 2025-12-26 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_instruction_remove_step_instruction_stepinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepinstruction',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
