# Generated by Django 6.0 on 2025-12-27 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_stepinstruction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.step'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StepInstruction',
        ),
    ]
