# Generated by Django 6.0 on 2025-12-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_instruction_number_instruction_step_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='instruction_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='number',
        ),
    ]
