# Generated by Django 6.0 on 2025-12-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_rename_instruction_text_instruction_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
