# Generated by Django 6.0 on 2026-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='utensil',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
