# Generated by Django 6.0 on 2026-01-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_ingredient_image_utensil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alternatives',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usually_stocked',
            field=models.BooleanField(default=True),
        ),
    ]
