# Generated by Django 6.0 on 2026-01-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_ingredient_alternatives_ingredient_usually_stocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
