# Generated by Django 6.0 on 2026-01-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
