# Generated by Django 6.0 on 2026-01-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='location',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='location1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location1', to='recipes.location'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='location2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location2', to='recipes.location'),
        ),
    ]
