# Generated by Django 6.0 on 2026-01-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_remove_ingredient_location_ingredient_location1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alternatives',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mögliche Alternative(n)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Zutat'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='location1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location1', to='recipes.location', verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='location2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location2', to='recipes.location', verbose_name='Alternativer Lagerort'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='usually_stocked',
            field=models.BooleanField(default=True, verbose_name='normalerweise vorhanden'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step', verbose_name='Schritt'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Koch/Backzeit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='experimental',
            field=models.BooleanField(default=False, verbose_name='Noch in Erprobung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Anmerkungen'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(max_length=100, verbose_name='Zubereitungszeit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200, verbose_name='Rezept'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quelle'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sweet',
            field=models.BooleanField(default=False, verbose_name='Süß'),
        ),
        migrations.AlterField(
            model_name='recipeutensil',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Rezept'),
        ),
        migrations.AlterField(
            model_name='recipeutensil',
            name='utensil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.utensil', verbose_name='Utensil'),
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Rezept'),
        ),
        migrations.AlterField(
            model_name='stepingredient',
            name='alternatives',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mögliche Alternative(n)'),
        ),
        migrations.AlterField(
            model_name='stepingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Zutat'),
        ),
        migrations.AlterField(
            model_name='stepingredient',
            name='quantity',
            field=models.CharField(max_length=200, verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='stepingredient',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.step', verbose_name='Schritt'),
        ),
        migrations.AlterField(
            model_name='stepingredient',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.location', verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='utensil_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Utensil'),
        ),
    ]
